
Demo Lan 1:

--Sao luu vao 3 file .bak
BACKUP DATABASE QLNV
TO DISK =N'C:\Full.bak'
WITH FORMAT

BACKUP DATABASE QLNV
TO DISK =N'C:\Diff.bak'
WITH FORMAT, DIFFERENTIAL

BACKUP LOG QLNV
TO DISK =N'C:\TailLog.bak'
WITH FORMAT, NO_TRUNCATE

--Phuc hoi tu 3 file .bak
use master
go

RESTORE DATABASE QLNV
FROM DISK =N'C:\Full.bak'
WITH NORECOVERY

RESTORE DATABASE QLNV
FROM DISK =N'C:\Diff.bak'
WITH NORECOVERY

RESTORE LOG QLNV
FROM DISK =N'C:\TailLog.bak'
WITH RECOVERY

Demo Lan 2:

--Sao luu vao 1 file .bak

BACKUP DATABASE QLNV
TO DISK =N'C:\QLNV.bak'
WITH FORMAT

BACKUP DATABASE QLNV
TO DISK =N'C:\QLNV.bak'
WITH DIFFERENTIAL

BACKUP LOG QLNV
TO DISK =N'C:\QLNV.bak'
WITH NO_TRUNCATE

-- Phuc hoi tu 1 file .bak
use master
go

RESTORE DATABASE QLNV
FROM DISK =N'C:\QLNV.bak'
WITH FILE=1, NORECOVERY
go
RESTORE DATABASE QLNV
FROM DISK =N'C:\QLNV.bak'
WITH FILE=2, NORECOVERY
go
RESTORE LOG QLNV
FROM DISK =N'C:\QLNV.bak'
WITH FILE=3, RECOVERY

Demo Lan 3:

--Sao luu vao 2 file .bak:
-- Full, TailLog vo 1 file: Full_TailLog.bak
-- Diff vo 1 file Diff.bak

BACKUP DATABASE QLNV
TO DISK =N'C:\Full_TailLog.bak'
WITH FORMAT

BACKUP DATABASE QLNV
TO DISK =N'C:\Diff.bak'
WITH FORMAT, DIFFERENTIAL

BACKUP LOG QLNV
TO DISK =N'C:\Full_TailLog.bak'
WITH NO_TRUNCATE

-- Phuc hoi tu 2 file .bak
use master
go

RESTORE DATABASE QLNV
FROM DISK =N'C:\Full_TailLog.bak'
WITH FILE=1, NORECOVERY
go
RESTORE DATABASE QLNV
FROM DISK =N'C:\Diff.bak'
WITH FILE=1, NORECOVERY
go
RESTORE LOG QLNV
FROM DISK =N'C:\Full_TailLog.bak'
WITH FILE=2, RECOVERY